### ISSUE TITLE
Using PKG_CONFIG_ALLOW_SYSTEM_CFLAGS/LIBS instead of --keep-system-cflags/libs

### ISSUE THREAD

**Issue by absolutelynothinghere** [skeeto/u-config#4]
First off, thank you so much for creating u-config! I've been looking forever for such a project.

Second, I would like to suggest using the environment variables `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` and `PKG_CONFIG_ALLOW_SYSTEM_LIBS` instead of relying only on the command line flags `--keep-system-cflags` and `--keep-system-libs`, as said flags are not used by the original pkg-config and hence are not portable... This would greatly help when writing scripts that support both pkg-config and u-config.

**Comment by skeeto** [comment]
Glad you've found u-config useful! Does the env-allow-system-flags branch 
work for you? In testing I caught a minor bug in the Win32 platform layer: 
It didn't distinguish between empty and unset variables. So the feature 
will also come with a small fix for that platform.

**Comment by absolutelynothinghere** [comment]
>Does the env-allow-system-flags branch work for you?

Seems to work fine after a quick test, thank you!
